<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ATS American Roadtrip Car Patcher</AssemblyName>
    <RootNamespace>TruckersToolKit</RootNamespace>
    <Platforms>AnyCPU</Platforms>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Cli/**" />
    <None Remove="Cli/**" />
    <Compile Remove="Tests/**" />
    <None Remove="Tests/**" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\app.ico" LogicalName="app.ico" />
    <EmbeddedResource Include="Assets\logo.png" LogicalName="logo.png" />
    <EmbeddedResource Include="CHANGELOG.md" LogicalName="CHANGELOG.md" />
  </ItemGroup>
</Project>
